/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_gui;

import java.awt.Component;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A
 */
public class SQL_GUI2 extends javax.swing.JFrame {

    
   
	/**
	 * Creates new form SQL_GUI2
	 */
	public SQL_GUI2() {
		initComponents();
		
		tblModel = (DefaultTableModel) jTable1.getModel();
		KDB = new KisiDBisleri(connectionUrl, user, pass);
		tblModel.setColumnIdentifiers(TableColName);
	}
	
	private DefaultTableModel tblModel;
	private String connectionUrl = "jdbc:sqlserver://A:1433;databaseName=IKVT;";
	private String user="AJP", pass="9900";
	String TableColName[] = { "No", "Ad", "Soyad", "TC", "Adres", "Telefon", "Mail", "Bölüm", "Maaş", "Kayıt", "Görev" };	// tabloda sütun başlıkları
	private KisiDBisleri KDB; // = new KisiDBisleri(connectionUrl, user, pass);

	private boolean TablodanVeriAl()
	{
		boolean sonuc=false;
		if (tblModel.getRowCount() >= 0 ) {
			int rowIndex = jTable1.getSelectedRow();
			int colIndex = jTable1.getSelectedColumn();

			if (rowIndex>=0 && colIndex>=0)
			{
				Vector row = tblModel.getDataVector().elementAt(rowIndex);
				jtf_Kid.setText(row.elementAt(0).toString());
				jtf_Adi.setText(row.elementAt(1).toString());
                                jtf_Soyad.setText(row.elementAt(2).toString());
                                jtf_Adres.setText(row.elementAt(3).toString());
                                jtf_TC.setText(row.elementAt(4).toString());
                                jtf_Tel.setText(row.elementAt(5).toString());
                                jtf_Mail.setText(row.elementAt(6).toString());
                                jtf_Bolum.setText(row.elementAt(7).toString());
                                jtf_Maas.setText(row.elementAt(8).toString());
                                jtf_Kayit.setText(row.elementAt(9).toString());
                                jtf_Gorev.setText(row.elementAt(10).toString());
                                
			}
			else
				JOptionPane.showMessageDialog(this,	"Tabloda secim yapilmadi!");
				//	tblModel.getDataVector().elementAt(rowIndex).elementAt(colIndex));	
		}		
		return sonuc;
	}

	private int KayitlariTabloyaYaz()
	{
		int say = 0;
		// clear table rows
		while (tblModel.getRowCount()>0)
			tblModel.removeRow(0);

		ArrayList<Kisi> Kisiler = KDB.KisiListesi(); //new ArrayList<>();
		
		for (Kisi k: Kisiler) {
			String data[] = {String.valueOf(k.getId()), k.getAdi(), k.getSoyad(), k.getAdres(), k.getTC(), k.getTel(), k.getMail(), k.getBolum(), k.getMaas(), k.getKayit(), k.getGorev()};
			tblModel.addRow(data);
			say++;
		}
		
        // Handle any errors that may have occurred.
		return say;
	}

	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtf_Adi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtf_Soyad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtf_Adres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtf_TC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtf_Kid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtf_Tel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtf_Mail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtf_Maas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtf_Bolum = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtf_Gorev = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtf_Kayit = new javax.swing.JTextField();
        jButton_Listele = new javax.swing.JButton();
        jButton_Ekle = new javax.swing.JButton();
        jButton_Gucelle = new javax.swing.JButton();
        psil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 188, 19));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Ad", "Soyad", "Tc", "Adres", "Telefon", "Mail", "Bölüm", "Maaş", "Kayıt", "Görev"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel2.setText("Ad:");

        jLabel5.setText("Soyad:");

        jtf_Soyad.setText("                       ");

        jLabel4.setText("TC:");

        jtf_Adres.setText("                    ");
        jtf_Adres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_AdresActionPerformed(evt);
            }
        });

        jLabel6.setText("Adres:");

        jtf_TC.setText("                      ");
        jtf_TC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_TCActionPerformed(evt);
            }
        });

        jLabel1.setText("Kayıt No:");

        jtf_Kid.setEditable(false);
        jtf_Kid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_KidActionPerformed(evt);
            }
        });

        jLabel3.setText("Telefon:");

        jLabel7.setText("Mail:");

        jtf_Mail.setText("                                      ");

        jLabel9.setText("Maaş:");

        jtf_Maas.setText("                               ");
        jtf_Maas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_MaasActionPerformed(evt);
            }
        });

        jLabel8.setText("Bölüm:");

        jtf_Bolum.setText("                                ");
        jtf_Bolum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_BolumActionPerformed(evt);
            }
        });

        jLabel11.setText("Görev:");

        jtf_Gorev.setText("                          ");

        jLabel10.setText("Kayıt Tarihi");

        jButton_Listele.setText("Listele");
        jButton_Listele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ListeleActionPerformed(evt);
            }
        });

        jButton_Ekle.setText("Yeni Ekle");
        jButton_Ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EkleActionPerformed(evt);
            }
        });

        jButton_Gucelle.setText("Guncelle");
        jButton_Gucelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GucelleActionPerformed(evt);
            }
        });

        psil.setText("İleri");
        psil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_Mail, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtf_Maas, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtf_Bolum, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_Gorev, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel10)
                                .addGap(32, 32, 32)
                                .addComponent(jtf_Kayit, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_Adi, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_Soyad, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_Adres, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Gucelle, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Ekle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(psil, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Listele, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_Kid, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtf_Kid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_Adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jtf_Soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jtf_Adres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jtf_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Listele)
                            .addComponent(jButton_Ekle))))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtf_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jtf_Mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtf_Maas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Gucelle)
                    .addComponent(psil))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtf_Bolum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jtf_Gorev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jtf_Kayit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_GucelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GucelleActionPerformed
        int k = KDB.KisiGuncellle(jtf_Kid.getText(), jtf_Adi.getText(), jtf_Soyad.getText(), jtf_TC.getText(), jtf_Adres.getText(), jtf_Tel.getText(), jtf_Mail.getText(), jtf_Bolum.getText(), jtf_Maas.getText(), jtf_Kayit.getText(), jtf_Gorev.getText());
        if (k>0)
        {
            jtf_Kid.setText("");			jtf_Adi.setText("");					jtf_Soyad.setText("");			jtf_TC.setText("");			jtf_Adres.setText("");  	jtf_Tel.setText("");			jtf_Mail.setText("");			jtf_Bolum.setText("");			jtf_Maas.setText("");			jtf_Kayit.setText("");			jtf_Gorev.setText("");
            KayitlariTabloyaYaz();
        }
    }//GEN-LAST:event_jButton_GucelleActionPerformed

    private void jButton_ListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ListeleActionPerformed
        KayitlariTabloyaYaz();
    }//GEN-LAST:event_jButton_ListeleActionPerformed

    private void jButton_EkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EkleActionPerformed
        int k = KDB.KisiEkle(jtf_Kid.getText(), jtf_Adi.getText(), jtf_Soyad.getText(), jtf_TC.getText(), jtf_Adres.getText(), jtf_Tel.getText(), jtf_Mail.getText(), jtf_Bolum.getText(), jtf_Maas.getText(), jtf_Kayit.getText(), jtf_Gorev.getText());
        if (k>0)
        {
            jtf_Kid.setText("");			jtf_Adi.setText("");			jtf_Soyad.setText("");			jtf_TC.setText("");			jtf_Adres.setText("");            jtf_Tel.setText("");                  jtf_Mail.setText("");			jtf_Bolum.setText("");			jtf_Maas.setText("");			jtf_Kayit.setText("");			jtf_Gorev.setText("");
            KayitlariTabloyaYaz();
        }
    }//GEN-LAST:event_jButton_EkleActionPerformed

    private void jtf_MaasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_MaasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_MaasActionPerformed

    private void jtf_BolumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_BolumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_BolumActionPerformed

    private void jtf_TCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_TCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_TCActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        TablodanVeriAl();
        jTable1.clearSelection();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jtf_AdresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_AdresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_AdresActionPerformed

    private void jtf_KidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_KidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_KidActionPerformed

    private void psilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psilActionPerformed

          Personaldelete frame = new Personaldelete();
         frame.setVisible(true);
         this.dispose();

    }//GEN-LAST:event_psilActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(SQL_GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(SQL_GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(SQL_GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SQL_GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SQL_GUI2().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Ekle;
    private javax.swing.JButton jButton_Gucelle;
    private javax.swing.JButton jButton_Listele;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtf_Adi;
    private javax.swing.JTextField jtf_Adres;
    private javax.swing.JTextField jtf_Bolum;
    private javax.swing.JTextField jtf_Gorev;
    private javax.swing.JTextField jtf_Kayit;
    private javax.swing.JTextField jtf_Kid;
    private javax.swing.JTextField jtf_Maas;
    private javax.swing.JTextField jtf_Mail;
    private javax.swing.JTextField jtf_Soyad;
    private javax.swing.JTextField jtf_TC;
    private javax.swing.JTextField jtf_Tel;
    private javax.swing.JButton psil;
    // End of variables declaration//GEN-END:variables
}
